# Generated by Django 5.0.6 on 2024-05-28 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_alter_verificationotp_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verificationotp',
            name='user',
        ),
        migrations.AddField(
            model_name='verificationotp',
            name='email',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
    ]
