# Generated by Django 5.0.6 on 2024-05-28 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_remove_verificationotp_user_verificationotp_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationotp',
            name='otp',
            field=models.CharField(max_length=6, unique=True),
        ),
    ]
